baseurl = "https://fsnotify.org"
languageCode = "en-us"
title = "fsnotify"

[permalinks]
post = "/:filename/"

[Params]
Description = "File system notifications for Go."
GaugesId = "54a4d7e5e32bb42c26167825"

[[menu.main]]
name = "Source Code"
url = "https://github.com/go-fsnotify/fsnotify"

[[menu.main]]
name = "Documentation"
url = "https://godoc.org/gopkg.in/fsnotify.v1"

[[menu.main]]
name = "Twitter"
url = "https://twitter.com/gofsnotify"
