baseurl = "https://fsnotify.org/"
languageCode = "en-us"
title = "fsnotify"
theme = "hyde"

[permalinks]
post = "/:filename/"

[Params]
description = "File system notifications for Go."

[[menu.main]]
name = "Source Code"
url = "https://github.com/fsnotify/fsnotify"

[[menu.main]]
name = "Documentation"
url = "https://godoc.org/github.com/fsnotify/fsnotify"

[[menu.main]]
name = "Twitter"
url = "https://twitter.com/fsnotify"
